### ISSUE TITLE
bug(workflows): UnhandledPromiseRejectionWarning when using the labeler

### ISSUE THREAD

**Issue by thijsvtol** [Videndum/utilities#11]
## Describe the bug

The [labeler workflow](https://github.com/Videndum/label-mastermind) does not work because it's trying to create a new logger from utilities (this repo) and is looking for localization which can't be found.
![image](https://user-images.githubusercontent.com/43065692/134814814-527afc6e-68f6-4242-88f9-28bceeff0029.png)

## Bug Checklist

- [x] Have reproduced on my application version
- [x] Have reproduced on a clean installation
- [x] Have reproduced on a development build
- [x] Have included logs or screenshots
- [ ] Have contacted support via the official website
- [ ] Have asked the community for guidance
- [ ] Have linked any related issues
- [x] Bug confirmed by @thijsvtol & @netail

**Comment by thijsvtol** [comment]
I was using the wrong versioning source in the labeler config file. However the error still have to been catched.

**Comment by TGTGamer** [comment]
> I was using the wrong versioning source in the labeler config file. However the error still have to been catched.

Heya, sorry about the delayed response. This is an issue to do with the way the code has been packaged. I will be working on it today. Please hang in there while I fix this issue
